spring:
  application:
    name: blog
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf8
    username: root
    password: root
  thymeleaf:
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false
  resources: 
    static-locations: classpath:/    
mybatis:
  mapperLocations: classpath:net/nonego/blog/dao/xml/*.xml
  typeAliasesPackage: net.nonego.blog.dao.model